version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "octocat"
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: "NPM"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "octocat"
    commit-message:
      prefix: "GitHub-Actions"
